"""Multi-agent research pipeline built on Claude tool use.

Three specialist analysts run in parallel, each with its own system prompt and
tool subset, executing a manual tool-use loop against the platform's internal
services. A final synthesis call merges their findings into a cited brief.

The Anthropic client is injected so tests can substitute a stub.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Any, Callable

from app.core.logging import get_logger
from app.services.research.tools import TOOL_DEFINITIONS, ResearchToolbox

logger = get_logger("app.services.research.agents")

DISCLAIMER = (
    "This report is generated by AI agents from public data for educational "
    "purposes. It is NOT investment advice."
)


@dataclass(frozen=True)
class AgentSpec:
    name: str
    title: str
    system: str
    tools: tuple[str, ...]


# Every agent gets the same closing instruction: this project runs on a hard
# per-day USD budget (see research.py's provider selection), so token-frugal
# behavior is a functional requirement, not a nicety. Two tool calls is enough
# for every tool subset below (each agent has 2-4 narrow, purpose-built tools);
# the max_iterations cap in run_agent is a backstop, not the primary limiter.
_EFFICIENCY_NOTE = (
    " Be efficient: call at most 2 tools (skip the rest if the picture is "
    "already clear), then answer. Do not repeat a tool call you already made."
)

AGENT_SPECS: tuple[AgentSpec, ...] = (
    AgentSpec(
        name="technical",
        title="Technical Analyst",
        system=(
            "You are a technical analyst on an equity/crypto research desk. "
            "Analyze the requested symbol using your tools: current quote, price "
            "history, technical indicators, and the platform's baseline forecast. "
            "Assess trend, momentum, and notable levels. Reference concrete numbers "
            "from tool results — never invent data. If a tool fails, work with what "
            "you have and say so. Finish with a 3-5 sentence summary of the "
            "technical picture, including one thing that would invalidate your read."
            + _EFFICIENCY_NOTE
        ),
        tools=("get_quote", "get_price_history", "get_technical_indicators", "get_forecast"),
    ),
    AgentSpec(
        name="sentiment",
        title="News & Sentiment Analyst",
        system=(
            "You are a news and sentiment analyst on a research desk. Use your tools "
            "to fetch the latest headlines and sentiment scores for the requested "
            "symbol. Identify the dominant narrative, any catalysts, and whether "
            "coverage skews positive or negative. Quote or cite specific headlines "
            "(title + source) — never invent articles. If there is little coverage, "
            "say so plainly rather than padding. Finish with a 3-5 sentence summary "
            "of the news picture."
            + _EFFICIENCY_NOTE
        ),
        tools=("get_quote", "get_news_sentiment"),
    ),
    AgentSpec(
        name="risk",
        title="Risk Analyst",
        system=(
            "You are a risk analyst on a research desk. Use your tools to assess "
            "realized volatility, drawdown within the recent window, and anomalous "
            "trading days for the requested symbol. Focus on what could go wrong "
            "for a holder: volatility regime, unusual moves, data quality gaps. "
            "Reference concrete numbers from tool results — never invent data. "
            "Finish with a 3-5 sentence summary and a qualitative risk rating "
            "(low / moderate / elevated / high) with justification."
            + _EFFICIENCY_NOTE
        ),
        tools=("get_quote", "get_price_history", "get_anomalies"),
    ),
)


@dataclass
class Usage:
    input_tokens: int = 0
    output_tokens: int = 0

    def add(self, response: Any) -> None:
        usage = getattr(response, "usage", None)
        if usage is not None:
            self.input_tokens += getattr(usage, "input_tokens", 0) or 0
            self.output_tokens += getattr(usage, "output_tokens", 0) or 0


@dataclass
class AgentResult:
    name: str
    title: str
    text: str
    tool_calls: list[dict[str, Any]] = field(default_factory=list)
    error: str | None = None


@dataclass
class ResearchOutcome:
    symbol: str
    asset_type: str
    model: str
    sections: list[AgentResult]
    synthesis: str
    usage: Usage


def _emit(on_event: Callable[[dict[str, Any]], None] | None, event: dict[str, Any]) -> None:
    """Fire an event to the optional callback. A dead client / buggy callback
    must never break a research run, so any exception is swallowed."""
    if on_event is None:
        return
    try:
        on_event(event)
    except Exception:  # noqa: BLE001 - callback errors must never sink a run
        logger.warning("Research on_event callback raised", exc_info=True)


def _text_from(response: Any) -> str:
    parts = [
        block.text for block in response.content if getattr(block, "type", None) == "text"
    ]
    return "\n".join(parts).strip()


async def run_agent(
    client: Any,
    model: str,
    spec: AgentSpec,
    symbol: str,
    toolbox: ResearchToolbox,
    usage: Usage,
    max_iterations: int = 3,
    on_event: Callable[[dict[str, Any]], None] | None = None,
) -> AgentResult:
    """Run one analyst's tool-use loop until it stops calling tools."""
    _emit(on_event, {"type": "agent_started", "agent": spec.name, "title": spec.title})
    tools = [TOOL_DEFINITIONS[name] for name in spec.tools]
    messages: list[dict[str, Any]] = [
        {
            "role": "user",
            "content": (
                f"Analyze {symbol} ({toolbox.asset_type.value}). Use your tools to "
                "gather data before drawing conclusions."
            ),
        }
    ]
    result = AgentResult(name=spec.name, title=spec.title, text="")

    try:
        for _ in range(max_iterations):
            response = await client.messages.create(
                model=model,
                max_tokens=600,
                system=spec.system,
                tools=tools,
                messages=messages,
            )
            usage.add(response)

            if response.stop_reason != "tool_use":
                result.text = _text_from(response)
                _emit(
                    on_event,
                    {"type": "agent_completed", "agent": spec.name, "ok": result.error is None},
                )
                return result

            tool_uses = [
                block for block in response.content if getattr(block, "type", None) == "tool_use"
            ]
            messages.append({"role": "assistant", "content": response.content})

            tool_results: list[dict[str, Any]] = []
            for block in tool_uses:
                payload, is_error = await toolbox.execute(block.name, dict(block.input))
                result.tool_calls.append({"tool": block.name, "input": dict(block.input)})
                _emit(
                    on_event,
                    {
                        "type": "tool_call",
                        "agent": spec.name,
                        "tool": block.name,
                        "input": dict(block.input),
                    },
                )
                tool_results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": payload,
                        "is_error": is_error,
                    }
                )
            # All results for one assistant turn go back in a single user message.
            messages.append({"role": "user", "content": tool_results})

        # Iteration cap hit: ask for a final answer without tools.
        messages.append(
            {
                "role": "user",
                "content": "Stop gathering data and write your final summary now.",
            }
        )
        response = await client.messages.create(
            model=model,
            max_tokens=600,
            system=spec.system,
            messages=messages,
        )
        usage.add(response)
        result.text = _text_from(response)
        _emit(on_event, {"type": "agent_completed", "agent": spec.name, "ok": result.error is None})
        return result
    except Exception as exc:  # noqa: BLE001 - one failed analyst must not sink the run
        logger.warning(
            "Research agent failed",
            extra={"agent": spec.name, "symbol": symbol, "error": str(exc)},
        )
        result.error = str(exc)
        result.text = f"({spec.title} unavailable: {exc})"
        _emit(on_event, {"type": "agent_completed", "agent": spec.name, "ok": False})
        return result


SYNTHESIS_SYSTEM = (
    "You are the lead analyst compiling a research brief from your team's notes. "
    "Write a concise markdown report with these sections:\n"
    "## Overview — 2-3 sentences on the asset and the headline takeaway.\n"
    "## Technical Picture\n## News & Sentiment\n## Risk Assessment\n"
    "## Bottom Line — 3-5 sentences reconciling the analysts, including where "
    "they disagree and what to watch next.\n\n"
    "Ground every claim in the analysts' notes; cite figures and headlines they "
    "reported. Do not invent data. Where an analyst was unavailable, note the gap. "
    "Do not give buy/sell recommendations."
)


async def synthesize(
    client: Any,
    model: str,
    symbol: str,
    asset_type: str,
    sections: list[AgentResult],
    usage: Usage,
) -> str:
    notes = "\n\n".join(
        f"### {section.title}\n{section.text}" for section in sections
    )
    response = await client.messages.create(
        model=model,
        max_tokens=1200,
        system=SYNTHESIS_SYSTEM,
        messages=[
            {
                "role": "user",
                "content": (
                    f"Compile the research brief for {symbol} ({asset_type}) from "
                    f"these analyst notes:\n\n{notes}"
                ),
            }
        ],
    )
    usage.add(response)
    return _text_from(response)


async def run_research(
    client: Any,
    model: str,
    symbol: str,
    toolbox: ResearchToolbox,
    max_iterations: int = 3,
    on_event: Callable[[dict[str, Any]], None] | None = None,
) -> ResearchOutcome:
    """Run all analysts in parallel, then synthesize their findings."""
    usage = Usage()
    sections = list(
        await asyncio.gather(
            *(
                run_agent(
                    client, model, spec, symbol, toolbox, usage, max_iterations, on_event=on_event
                )
                for spec in AGENT_SPECS
            )
        )
    )
    _emit(on_event, {"type": "synthesis_started"})
    synthesis = await synthesize(
        client, model, symbol, toolbox.asset_type.value, sections, usage
    )
    return ResearchOutcome(
        symbol=symbol,
        asset_type=toolbox.asset_type.value,
        model=model,
        sections=sections,
        synthesis=f"{synthesis}\n\n---\n*{DISCLAIMER}*",
        usage=usage,
    )
